# Generated by Django 4.2.2 on 2023-06-20 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contas',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=15, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=15, verbose_name='Sobrenome')),
                ('user', models.CharField(max_length=10, verbose_name='Usuario')),
                ('senha', models.CharField(max_length=25, verbose_name='Senha')),
                ('email', models.EmailField(max_length=25, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados', models.FileField(upload_to='Arquivos', verbose_name='Dados')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.contas', verbose_name='Nome')),
            ],
        ),
    ]
