# Generated by Django 4.2.2 on 2023-06-16 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('sobrenome', models.CharField(max_length=15)),
                ('user', models.CharField(max_length=10)),
                ('senha', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados', models.FileField(upload_to='Arquivos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.contas')),
            ],
        ),
    ]
