# Generated by Django 4.2.2 on 2023-06-16 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas',
            name='email',
            field=models.EmailField(max_length=25, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contas',
            name='nome',
            field=models.CharField(max_length=15, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='contas',
            name='senha',
            field=models.CharField(max_length=25, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='contas',
            name='sobrenome',
            field=models.CharField(max_length=15, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='contas',
            name='user',
            field=models.CharField(max_length=10, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dados',
            field=models.FileField(upload_to='Arquivos', verbose_name='Dados'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.contas', verbose_name='Nome'),
        ),
    ]
